version: "3.9"

services:
  lumen:
    build: .
    image: lumen:latest
    container_name: lumen
    stdin_open: true
    tty: true
    volumes:
      - ./examples:/home/lumen/examples
      - ./stdlib:/usr/local/share/lumen/stdlib
    command: ["run", "examples/hello.nv"]

  lumen-repl:
    build: .
    image: lumen:latest
    container_name: lumen-repl
    stdin_open: true
    tty: true
    volumes:
      - ./examples:/home/lumen/examples
      - ./stdlib:/usr/local/share/lumen/stdlib
    command: ["repl"]
