[package]
name = "lumen-vm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Máquina virtual stack-based para el lenguaje LÚMEN — ejecuta bytecode .nvc"
keywords = ["lumen", "language", "vm", "virtual-machine", "educational"]

[dependencies]
lumen-codegen = { path = "../lumen-codegen" }
serde_json.workspace = true
thiserror.workspace = true
regex = "1"
reqwest = { version = "0.12", features = ["blocking"] }
unicode-normalization = "0.1"

[dev-dependencies]
lumen-lexer = { path = "../lumen-lexer" }
lumen-parser = { path = "../lumen-parser" }
lumen-sema = { path = "../lumen-sema" }
lumen-ir = { path = "../lumen-ir" }
