[package]
name = "lumen-doc"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Generador de documentación para LÚMEN — produce HTML desde comentarios ///"
keywords = ["lumen", "language", "docs", "documentation", "html"]

[[bin]]
name = "lumen-doc"
path = "src/main.rs"

[dependencies]
lumen-lexer = { path = "../lumen-lexer" }
lumen-parser = { path = "../lumen-parser" }
