[package]
name = "lumen-wasm"
version.workspace = true
edition.workspace = true
description = "LÚMEN WebAssembly runtime — ejecuta LÚMEN en el navegador"
license = "MIT"
repository = "https://github.com/omarPVP123131/Lumen"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["wasm"]
wasm = ["wasm-bindgen", "js-sys", "console_error_panic_hook"]
wasi = []

[dependencies]
wasm-bindgen = { version = "0.2", optional = true }
js-sys = { version = "0.3", optional = true }
console_error_panic_hook = { version = "0.1", optional = true }
lumen-lexer = { path = "../lumen-lexer" }
lumen-parser = { path = "../lumen-parser" }
lumen-sema = { path = "../lumen-sema" }
lumen-ir = { path = "../lumen-ir" }
lumen-codegen = { path = "../lumen-codegen" }
lumen-vm = { path = "../lumen-vm", default-features = false, features = ["extra"] }
