[package]
name = "lumen-aot"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Compilación Ahead-of-Time para LÚMEN — genera binarios nativos vía LLVM"
keywords = ["lumen", "language", "aot", "llvm", "native", "compiler"]

[dependencies]
lumen-ir = { path = "../lumen-ir" }
cranelift = { version = "0.132", features = ["frontend"] }
cranelift-module = "0.132"
cranelift-object = "0.132"
cranelift-native = "0.132"
cranelift-jit = "0.132"
target-lexicon = "0.12"
